In [1]:
import numpy as np
A =np.array([[1, 2], 
             [3, 4]])
print(A)
print("dtype of matrix A", A.dtype)

[[1 2]
 [3 4]]
dtype of matrix A int32


In [12]:
# B = np.array([[1, 2],
#               [3, 4]], dtype=np.float32)

# print(B)
# print("dtype of matrix B: ", B.dtyp

import numpy as np
B = np.array([[1, 2],
              [3, 4]], dtype=np.float32)
print(B)



[[1. 2.]
 [3. 4.]]


In [3]:
R = np.random.randn(2, 3)
print(R)

[[ 0.2807946  -0.48947757  0.29200577]
 [ 0.45728526  0.04329527  1.00421549]]


In [13]:
#Save numpy
import numpy as np
A = np.random.randn(3, 3)
A

array([[ 0.24807002,  1.50434875, -0.38985429],
       [-1.57882965,  0.76109241, -0.79202682],
       [-0.75973243, -0.77805153, -0.78317661]])

In [17]:
np.save("E:\Data Analyst", A)

In [21]:
import pandas as pd
    
np.save("E:\Data Analyst\np.npy", A)

OSError: [Errno 22] Invalid argument: 'E:\\Data Analyst\np.npy'

In [22]:
# Định dạng npy
np.save("E:\Data Analyst\np/A", A)
# Định dạng txt
np.savetxt("E:\Data Analyst\np/A.txt", A)
# List các file
!ls -a numpy_save

OSError: [Errno 22] Invalid argument: 'E:\\Data Analyst\np/A.npy'

In [23]:
A = df.values
print(A)

NameError: name 'df' is not defined

In [1]:
five_even_numbers = []
k_number = 1

while True:
    if k_number%2 == 0:
        five_even_numbers.append(k_number)
        if len(five_even_numbers) >=5:
            break
    k_number += 1
print(k_number)
print(five_even_numbers)

10
[2, 4, 6, 8, 10]
